### ISSUE TITLE
Boot-Loader size "BOOTSZ" Hfuse

### ISSUE THREAD

**Issue by minagerges** [Lauszus/Sanguino#14]
Hello!
Sorry if it's a dummy question.

On ATmega1284p, when I do "avr-size -A optiboot_atmega1284p.hex" I get the following:
> section   size     addr
> .sec1    472   130048
> .sec2      2   131070
> Total    474

This means that the boot-loader size is 474 bytes.  

The question is: Can I set Hfuse to DE (512 words) ?
Is it possible to recompile for different address and gain 512 bytes of PROGMEM

The confusing is that, boards.txt has Hfuse to DE, yet 130048 bytes only

**Comment by Lauszus** [comment]
Not that is not a mistake, it's 512 words (i.e. 16-bits) and __NOT__ 512 bytes. So it is actually 2*512=1024 bytes. This is indeed very confusing.

Here is an excellent "fuse calculator", which might help you in the future: http://www.engbedded.com/fusecalc/.
