### ISSUE TITLE
arduino-cli compatibility problem

### ISSUE THREAD

**Issue by Renaud11232** [Lauszus/Sanguino#17]
There is an issue when using Sanguino installed with the package manager on [arduino-cli](https://github.com/arduino/arduino-cli).
`arduino-cli` seems to be using the `-fno-fat-lto-objects` flag which is not available on `avr-gcc@4.8.1` according to [this issue](https://github.com/MCUdude/MicroCore/issues/20).

The problem is that this 3rd party hardware states in `package_lauszus_sanguino_index.json` that `avr-gcc@4.8.1-arduino5` is required and thus forces `arduino-cli` to use it which makes the compilation process fail with:
```
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
```
on Windows, and:
```
sorry - this program has been built without plugin support
```
on Linux.

When Sanguino is manually installed in `$SKETCHBOOK/hardware` it compiles sucessfully.

Using `avr-gcc@5.4.0-atmel3.6.1-arduino2` and `avrdude@6.3.0-arduino14` works fine.

Would it be possible to update the requirements ?

**Comment by kazooless** [comment]
The same failure message reported above for Linux appears on the MacOS version. Unfortunately, the older versions of ArduinoIDE won't run on the latest MacOS due to system changes in the OS.

**Comment by Lauszus** [comment]
@Renaud11232 thank you for reporting the issue. I just published a new release: https://github.com/Lauszus/Sanguino/commit/4aa3893ee97b69d46c37373a3693e43d25e7dd9d. Please test it and report back if you have any issues.
