### ISSUE TITLE
How can i fit an auto bed leveling sensor

### ISSUE THREAD

**Issue by GhassanYusuf** [Lauszus/Sanguino#23]
i am trying to add an inductive sn04 sensor and want to use Marlin 2.0 i always get an error, can you please help me out

**Comment by Ryder17z** [comment]
post the error so we can see what's happening

**Comment by GhassanYusuf** [comment]
I am trying to fit marlin 2.0 On It

This is the picture of the board
![](https://i.ibb.co/72X3SRS/s-l300.jpg)

This is the error
![](https://i.ibb.co/Y0fs4sT/2020-02-07-17h45-29.png)

Everything compiles very well but only the final step fails as you can see on the picture

**Comment by Ryder17z** [comment]
Does the file exist?

**Comment by GhassanYusuf** [comment]
I don't know, but it compiles on the older version of marlin, why in marlin 2.0 it does not compile

**Comment by Lauszus** [comment]
You should really post this question on one of the Marlin forums. This repository is simply so you can use your microcontroller with Arduino and has nothing to do with Marlin.

**Comment by Lauszus** [comment]
I'm going to close this, as it has not really anything to do with this hardware add-on.
