### ISSUE TITLE
Unable to Burn Bootloader on a Sanguino ATmega644P

### ISSUE THREAD

**Issue by mwalz** [Lauszus/Sanguino#8]
Hello,

I'm unable to Burn Bootloader on a Sanguino ATmega644P.

Settings:
Board: Sanguino
Processor: ATmega644P or ATmega644PA (16 MHz)
Programmer: Arduino as ISP

Serial Monitor does appear to work, it shows 'start' from the Arduino when it connects. This if for an original Huxley RepRap from late 2011 / early 2012. 

I keep getting the following output:

avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x39
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x3c
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xac
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xff
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xff
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xff
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0xff
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xff
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xff

I've tried multple Programmer settings with no success, do you have any suggestions?

Thanks!

**Comment by Lauszus** [comment]
Make sure that you have wired the ISP programmer correctly. Please see the following page: https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard.
Also have you disabled auto-reset on the Arduino you are trying to use as ISP?

**Comment by Lauszus** [comment]
@mwalz any updates?

**Comment by mwalz** [comment]
Apologies for the delayed response. I did have the jumper in place. I believe that was causing issues. In the process of removing it, the board was short circuited. I have another board on the way and hope to test is in the next few days.

Thanks for your initial answer and follow up. I will update by the end of this week.

**Comment by Lauszus** [comment]
@mwalz okay no problem. Please reopen if needed :)

**Comment by nkuck** [comment]
I am experiencing the same problem (avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x66) after unsuccessfully trying to upload Marlin FW to my Melzi board. All worked fine before. I can upload a sketch to a different Arduino board and all is fine. But when I try to upload Marlin to my printer, I get the message. Any suggestions? Thank for any direction. Could the boot loader have been corrupted? I can still print.

**Comment by nkuck** [comment]
Never mind. My error. Had the jumper pin connected on the board. All is good.

**Comment by nkuck** [comment]
Please do mind : ).
I thought that it was working but nope. Getting the common not in sync error. Jumper is in place and the board works fine as-is; just can't upload newer firmware. Ideas? Thanks any/everyone.

**Comment by Lauszus** [comment]
Have you tried to re-burn the bootloader?

**Comment by nkuck** [comment]
Not tried the bootloader as I read about it being complex.

Live simply!
You can only take with you what you have given.




On Sat, Jul 2, 2016 at 4:07 PM -0400, "Kristian Sloth Lauszus" <notifications@github.com> wrote:












Have you tried to re-burn the bootloader?

**Comment by Lauszus** [comment]
This add-on will not work with the standard bootloader, as this uses the improved optiboot bootloader.

**Comment by nkuck** [comment]
Are you suggesting that I attempt the optiboot bootloader?

Live simply!
You can only take with you what you have given.

		_____________________________

**Comment by Lauszus** [comment]
Yes. You need to install the add-on. Select the Sanguino and then burn the bootloaders. You should be able to find guides on how to burn the bootloader using a second Arduino online.

**Comment by nkuck** [comment]
Can I use the Arduino IDE with the computer plugged into the Sanguino board to simply upload the optiboot file to it?

**Comment by Lauszus** [comment]
No you will to use a second Arduino as a programmer. Please see: https://www.arduino.cc/en/Tutorial/ArduinoISP.

**Comment by nkuck** [comment]
But won't that require me unsoldering the chip from the Sanduino board? Am I confused?

Live simply!




On Sun, Jul 3, 2016 at 8:04 AM -0400, "Kristian Sloth Lauszus" <notifications@github.com> wrote:












No you will to use a second Arduino as a programmer. Please see: https://www.arduino.cc/en/Tutorial/ArduinoISP.

**Comment by Lauszus** [comment]
No it doesn't. You simply connect to the header labeled ICSP on the Sanguino board.

**Comment by nkuck** [comment]
Oh, got it. Will advise when successful. So, burn the bootloader then able to load the new firmware? Thanks for your support. 

Live simply!
You can only take with you what you have given.




On Sun, Jul 3, 2016 at 8:16 AM -0400, "Kristian Sloth Lauszus" <notifications@github.com> wrote:












No it doesn't. You simply connect to the header labeled ICSP on the Sanguino board.

**Comment by Lauszus** [comment]
Okay good. Yes exactly :)

**Comment by nkuck** [comment]
Oh, oh, I may need further handholding, like step-by-step directions. What connects to the ICSP pins on the Sanguino board? Sorry😱.

Live simply!
You can only take with you what you have given.

		_____________________________

**Comment by Lauszus** [comment]
Sorry I don't have time to do that. Please see: https://www.arduino.cc/en/Tutorial/ArduinoISP and https://learn.sparkfun.com/tutorials/installing-an-arduino-bootloader.

**Comment by comarius** [comment]
DON'T BUY  Sanguino  boards !!! Support sucks.

**Comment by nkuck** [comment]
Agree!

Noel Kuck

Live simply!

**Comment by Lauszus** [comment]
@comarius @nkuck please note that I am not affiliated with the people behind Sanguino. I simply published this repository, as I found that the official board add-on was outdated.

**Comment by Lauszus** [comment]
@comarius and @nkuck please note that it is now also possible to use this add-on with PlatformIO. This will allow you to upload to the board without having to upload the bootloader. Please see the instructions in the readme: https://github.com/Lauszus/Sanguino#platformio.
